package com.varun.quickconvert


data class Currency(val code: String, val name: String)

// data source for currencies.
val worldCurrencies = listOf(
    Currency("USD", "United States Dollar"),
    Currency("EUR", "Euro"),
    Currency("JPY", "Japanese Yen"),
    Currency("GBP", "British Pound"),
    Currency("INR", "Indian Rupee"),
    Currency("AUD", "Australian Dollar"),
    Currency("CAD", "Canadian Dollar"),
    Currency("CHF", "Swiss Franc"),
    Currency("CNY", "Chinese Yuan"),
    Currency("AED", "UAE Dirham"),
    Currency("AFN", "Afghan Afghani"),
    Currency("ALL", "Albanian Lek"),
    Currency("AMD", "Armenian Dram"),
    Currency("ANG", "Netherlands Antillian Guilder"),
    Currency("AOA", "Angolan Kwanza"),
    Currency("ARS", "Argentine Peso"),
    Currency("AWG", "Aruban Florin"),
    Currency("AZN", "Azerbaijani Manat"),
    Currency("BAM", "Bosnia-Herzegovina Convertible Mark"),
    Currency("BBD", "Barbadian Dollar"),
    Currency("BDT", "Bangladeshi Taka"),
    Currency("BGN", "Bulgarian Lev"),
    Currency("BHD", "Bahraini Dinar"),
    Currency("BIF", "Burundian Franc"),
    Currency("BMD", "Bermudan Dollar"),
    Currency("BND", "Brunei Dollar"),
    Currency("BOB", "Bolivian Boliviano"),
    Currency("BRL", "Brazilian Real"),
    Currency("BSD", "Bahamian Dollar"),
    Currency("BTN", "Bhutanese Ngultrum"),
    Currency("BWP", "Botswanan Pula"),
    Currency("BYN", "Belarusian Ruble"),
    Currency("BZD", "Belize Dollar"),
    Currency("CDF", "Congolese Franc"),
    Currency("CLP", "Chilean Peso"),
    Currency("COP", "Colombian Peso"),
    Currency("CRC", "Costa Rican Colón"),
    Currency("CUP", "Cuban Peso"),
    Currency("CVE", "Cape Verdean Escudo"),
    Currency("CZK", "Czech Koruna"),
    Currency("DJF", "Djiboutian Franc"),
    Currency("DKK", "Danish Krone"),
    Currency("DOP", "Dominican Peso"),
    Currency("DZD", "Algerian Dinar"),
    Currency("EGP", "Egyptian Pound"),
    Currency("ERN", "Eritrean Nakfa"),
    Currency("ETB", "Ethiopian Birr"),
    Currency("FJD", "Fijian Dollar"),
    Currency("FKP", "Falkland Islands Pound"),
    Currency("FOK", "Faroese Króna"),
    Currency("GEL", "Georgian Lari"),
    Currency("GGP", "Guernsey Pound"),
    Currency("GHS", "Ghanaian Cedi"),
    Currency("GIP", "Gibraltar Pound"),
    Currency("GMD", "Gambian Dalasi"),
    Currency("GNF", "Guinean Franc"),
    Currency("GTQ", "Guatemalan Quetzal"),
    Currency("GYD", "Guyanaese Dollar"),
    Currency("HKD", "Hong Kong Dollar"),
    Currency("HNL", "Honduran Lempira"),
    Currency("HRK", "Croatian Kuna"),
    Currency("HTG", "Haitian Gourde"),
    Currency("HUF", "Hungarian Forint"),
    Currency("IDR", "Indonesian Rupiah"),
    Currency("ILS", "Israeli New Shekel"),
    Currency("IMP", "Isle of Man Pound"),
    Currency("IQD", "Iraqi Dinar"),
    Currency("IRR", "Iranian Rial"),
    Currency("ISK", "Icelandic Króna"),
    Currency("JEP", "Jersey Pound"),
    Currency("JMD", "Jamaican Dollar"),
    Currency("JOD", "Jordanian Dinar"),
    Currency("KES", "Kenyan Shilling"),
    Currency("KGS", "Kyrgystani Som"),
    Currency("KHR", "Cambodian Riel"),
    Currency("KID", "Kiribati Dollar"),
    Currency("KMF", "Comorian Franc"),
    Currency("KRW", "South Korean Won"),
    Currency("KWD", "Kuwaiti Dinar"),
    Currency("KYD", "Cayman Islands Dollar"),
    Currency("KZT", "Kazakhstani Tenge"),
    Currency("LAK", "Laotian Kip"),
    Currency("LBP", "Lebanese Pound"),
    Currency("LKR", "Sri Lankan Rupee"),
    Currency("LRD", "Liberian Dollar"),
    Currency("LSL", "Lesotho Loti"),
    Currency("LYD", "Libyan Dinar"),
    Currency("MAD", "Moroccan Dirham"),
    Currency("MDL", "Moldovan Leu"),
    Currency("MGA", "Malagasy Ariary"),
    Currency("MKD", "Macedonian Denar"),
    Currency("MMK", "Myanma Kyat"),
    Currency("MNT", "Mongolian Tugrik"),
    Currency("MOP", "Macanese Pataca"),
    Currency("MRU", "Mauritanian Ouguiya"),
    Currency("MUR", "Mauritian Rupee"),
    Currency("MVR", "Maldivian Rufiyaa"),
    Currency("MWK", "Malawian Kwacha"),
    Currency("MXN", "Mexican Peso"),
    Currency("MYR", "Malaysian Ringgit"),
    Currency("MZN", "Mozambican Metical"),
    Currency("NAD", "Namibian Dollar"),
    Currency("NGN", "Nigerian Naira"),
    Currency("NIO", "Nicaraguan Córdoba"),
    Currency("NOK", "Norwegian Krone"),
    Currency("NPR", "Nepalese Rupee"),
    Currency("NZD", "New Zealand Dollar"),
    Currency("OMR", "Omani Rial"),
    Currency("PAB", "Panamanian Balboa"),
    Currency("PEN", "Peruvian Nuevo Sol"),
    Currency("PGK", "Papua New Guinean Kina"),
    Currency("PHP", "Philippine Peso"),
    Currency("PKR", "Pakistani Rupee"),
    Currency("PLN", "Polish Zloty"),
    Currency("PYG", "Paraguayan Guarani"),
    Currency("QAR", "Qatari Rial"),
    Currency("RON", "Romanian Leu"),
    Currency("RSD", "Serbian Dinar"),
    Currency("RUB", "Russian Ruble"),
    Currency("RWF", "Rwandan Franc"),
    Currency("SAR", "Saudi Riyal"),
    Currency("SBD", "Solomon Islands Dollar"),
    Currency("SCR", "Seychellois Rupee"),
    Currency("SDG", "Sudanese Pound"),
    Currency("SEK", "Swedish Krona"),
    Currency("SGD", "Singapore Dollar"),
    Currency("SHP", "Saint Helena Pound"),
    Currency("SLE", "Sierra Leonean Leone"),
    Currency("SLL", "Sierra Leonean Leone"),
    Currency("SOS", "Somali Shilling"),
    Currency("SRD", "Surinamese Dollar"),
    Currency("SSP", "South Sudanese Pound"),
    Currency("STN", "São Tomé and Príncipe Dobra"),
    Currency("SYP", "Syrian Pound"),
    Currency("SZL", "Swazi Lilangeni"),
    Currency("THB", "Thai Baht"),
    Currency("TJS", "Tajikistani Somoni"),
    Currency("TMT", "Turkmenistani Manat"),
    Currency("TND", "Tunisian Dinar"),
    Currency("TOP", "Tongan Pa'anga"),
    Currency("TRY", "Turkish Lira"),
    Currency("TTD", "Trinidad and Tobago Dollar"),
    Currency("TVD", "Tuvaluan Dollar"),
    Currency("TWD", "New Taiwan Dollar"),
    Currency("TZS", "Tanzanian Shilling"),
    Currency("UAH", "Ukrainian Hryvnia"),
    Currency("UGX", "Ugandan Shilling"),
    Currency("UYU", "Uruguayan Peso"),
    Currency("UZS", "Uzbekistan Som"),
    Currency("VES", "Venezuelan Bolívar"),
    Currency("VND", "Vietnamese Dong"),
    Currency("VUV", "Vanuatu Vatu"),
    Currency("WST", "Samoan Tala"),
    Currency("XAF", "CFA Franc BEAC"),
    Currency("XCD", "East Caribbean Dollar"),
    Currency("XDR", "Special Drawing Rights"),
    Currency("XOF", "CFA Franc BCEAO"),
    Currency("XPF", "CFP Franc"),
    Currency("YER", "Yemeni Rial"),
    Currency("ZAR", "South African Rand"),
    Currency("ZMW", "Zambian Kwacha"),
    Currency("ZWL", "Zimbabwean Dollar")
)